sudo: false
language: node_js
node_js: '4'
cache:
  directories: node_modules
before_script: npm prune
branches:
  except: /^v\d+\.\d+\.\d+$/
notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change
    on_failure: always
    on_start: false
  email: false
script: npm run test-ci
addons:
  sauce_connect: true
env:
  global:
  - secure: fUUCaHI/jFb2qjqBgCi1d0Yl7OMSDiFrAg3iBkGU9Ou3HGsTJDWPH4LynDt3wilSzkgj0tiIIUAMGhHReyixGeq3WSay/gzczxY6n4D/jmqgep/9FwC2Zh5p/Iwjj2413lQKadzIZR0Z8pkHRd0VwFZQ2VWwrQGPnTN9KH8JUj8=
  - secure: dyFY75oJWWxwEFZnxLzAcMLoo7lt5h9QVctoQt9H2s4GYi/IrYIA3OSlg8zT8kYLE3BSSN5P1aOtZAG6tCY0STPwFJ1ZniMLYa/5iGOqLyVXBr3hBExuTq151dM6qUzpU6ZzMIipOlik6wJSzOIyTejkFA7WQ0CHEscFdfNo9Ms=
